// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'project_item_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

ProjectItemModel _$ProjectItemModelFromJson(Map<String, dynamic> json) =>
    ProjectItemModel(
      id: json['id'] as int?,
      name: json['name'] as String?,
      description: json['description'] as String?,
      start: json['start'] as String?,
      end: json['end'] as String?,
      doneDate: json['done_date'],
      createdAt: json['created_at'] as String?,
      updatedAt: json['updated_at'] as String?,
      performPercent: json['perform_percent'] as int?,
      status: json['status'] as String?,
      projectType: json['project_type'] as String?,
      middlePoint: json['middle_point'] as String?,
      avatar: json['avatar'] as int?,
      avatarSrc: json['avatar_src'] as String?,
      ownerId: json['first_name'] as int?,
      tasks: (json['tasks'] as List<dynamic>?)
          ?.map((e) => TaskModel.fromJson(e as Map<String, dynamic>))
          .toList(),
      allTasksCount: json['all_tasks_count'] as int?,
      myTasksCount: json['my_tasks_count'] as int?,
      doneTasksCount: json['done_tasks_count'] as int?,
      managers: (json['managers'] as List<dynamic>?)
          ?.map((e) => ManagerModel.fromJson(e as Map<String, dynamic>))
          .toList(),
      members: (json['members'] as List<dynamic>?)
          ?.map((e) => MemberModel.fromJson(e as Map<String, dynamic>))
          .toList(),
      curators: (json['curators'] as List<dynamic>?)
          ?.map((e) => CuratorModel.fromJson(e as Map<String, dynamic>))
          .toList(),
      files: (json['files'] as List<dynamic>?)
          ?.map((e) => FileModel.fromJson(e as Map<String, dynamic>))
          .toList(),
      finSource: (json['fin_source'] as List<dynamic>?)
          ?.map((e) => e as String)
          .toList(),
      finSourceSumOther: json['finSourceSumOther'] as String?,
      zu: json['zu'] as String?,
      zu_number: json['zu_number'] as String?,
      zu_comment: json['zu_comment'] as String?,
      zuFileId: json['zu_file_id'] as String?,
      psd: json['psd'] as String?,
      psdFileId: json['psd_file_id'] as String?,
      gip: json['gip'] as String?,
      gip_number: json['gip_number'] as String?,
      gip_comment: json['gip_comment'] as String?,
      gipFileId: json['gip_file_id'] as String?,
      feo: json['feo'] as String?,
      feo_number: json['feo_number'] as String?,
      feo_comment: json['feo_comment'] as String?,
      feoFileId: json['feo_file_id'] as String?,
      businessPlanFileId: json['business_plan_file_id'] as String?,
      fin_econom: json['fin_econom'] as String?,
      fin_econom_comment: json['fin_econom_comment'] as String?,
      gprt: json['gprt'] as String?,
      gprt_comment: json['gprt_comment'] as String?,
      gprt_number: json['gprt_number'] as String?,
      dkz: json['dkz'] as String?,
      dkz_comment: json['dkz_comment'] as String?,
      dkz_number: json['dkz_number'] as String?,
      teo: json['teo'] as String?,
      teo_comment: json['teo_comment'] as String?,
      teo_number: json['teo_number'] as String?,
      psd_comment: json['psd_comment'] as String?,
      psd_number: json['psd_number'] as String?,
      budget: json['budget'] as String?,
      budget_status: json['budget_status'] as String?,
      budget_status_comment: json['budget_status_comment'] as String?,
      budget_comment: json['budget_comment'] as String?,
      competitive: json['competitive'] as String?,
      competitive_comment: json['competitive_comment'] as String?,
      smr: json['smr'] as String?,
      smr_comment: json['smr_comment'] as String?,
      business_plan: json['business_plan'] as String?,
      business_plan_comment: json['business_plan_comment'] as String?,
      marketing_plan: json['marketing_plan'] as String?,
      marketing_plan_comment: json['marketing_plan_comment'] as String?,
      fin_sum: json['fin_sum'] as int?,
      fin_source_sum_budget: json['fin_source_sum_budget'] as String?,
      fin_source_sum_investments: json['fin_source_sum_investments'] as String?,
      fin_source_sum_local_budget:
          json['fin_source_sum_local_budget'] as String?,
      fin_source_sum_other: json['fin_source_sum_other'] as String?,
      fin_source_sum_republican_budget:
          json['fin_source_sum_republican_budget'] as String?,
      commentCount: json['comment_count'] as int?,
    );

Map<String, dynamic> _$ProjectItemModelToJson(ProjectItemModel instance) =>
    <String, dynamic>{
      'id': instance.id,
      'name': instance.name,
      'description': instance.description,
      'start': instance.start,
      'end': instance.end,
      'gprt': instance.gprt,
      'gprt_number': instance.gprt_number,
      'gprt_comment': instance.gprt_comment,
      'dkz': instance.dkz,
      'dkz_number': instance.dkz_number,
      'dkz_comment': instance.dkz_comment,
      'teo': instance.teo,
      'teo_number': instance.teo_number,
      'teo_comment': instance.teo_comment,
      'psd': instance.psd,
      'psd_number': instance.psd_number,
      'psd_comment': instance.psd_comment,
      'competitive': instance.competitive,
      'competitive_comment': instance.competitive_comment,
      'smr': instance.smr,
      'smr_comment': instance.smr_comment,
      'budget': instance.budget,
      'budget_status': instance.budget_status,
      'budget_comment': instance.budget_comment,
      'budget_status_comment': instance.budget_status_comment,
      'zu': instance.zu,
      'zu_number': instance.zu_number,
      'zu_comment': instance.zu_comment,
      'gip': instance.gip,
      'gip_number': instance.gip_number,
      'gip_comment': instance.gip_comment,
      'feo': instance.feo,
      'feo_number': instance.feo_number,
      'feo_comment': instance.feo_comment,
      'business_plan': instance.business_plan,
      'business_plan_comment': instance.business_plan_comment,
      'fin_econom': instance.fin_econom,
      'fin_econom_comment': instance.fin_econom_comment,
      'marketing_plan': instance.marketing_plan,
      'marketing_plan_comment': instance.marketing_plan_comment,
      'fin_sum': instance.fin_sum,
      'fin_source_sum_budget': instance.fin_source_sum_budget,
      'fin_source_sum_investments': instance.fin_source_sum_investments,
      'fin_source_sum_local_budget': instance.fin_source_sum_local_budget,
      'fin_source_sum_other': instance.fin_source_sum_other,
      'fin_source_sum_republican_budget':
          instance.fin_source_sum_republican_budget,
      'done_date': instance.doneDate,
      'created_at': instance.createdAt,
      'updated_at': instance.updatedAt,
      'perform_percent': instance.performPercent,
      'status': instance.status,
      'project_type': instance.projectType,
      'middle_point': instance.middlePoint,
      'avatar': instance.avatar,
      'avatar_src': instance.avatarSrc,
      'first_name': instance.ownerId,
      'tasks': instance.tasks,
      'all_tasks_count': instance.allTasksCount,
      'my_tasks_count': instance.myTasksCount,
      'done_tasks_count': instance.doneTasksCount,
      'managers': instance.managers,
      'members': instance.members,
      'curators': instance.curators,
      'files': instance.files,
      'fin_source': instance.finSource,
      'finSourceSumOther': instance.finSourceSumOther,
      'zu_file_id': instance.zuFileId,
      'psd_file_id': instance.psdFileId,
      'gip_file_id': instance.gipFileId,
      'feo_file_id': instance.feoFileId,
      'business_plan_file_id': instance.businessPlanFileId,
      'comment_count': instance.commentCount,
    };
